import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// export default Home

const Index: NextPage = () => {
  return (
    <div className="container">

      <Head>
        <meta charSet="utf-8" />
        <title>The Roaming Review</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        {/* <link href="/styles/index.css" rel="stylesheet"></link> */}
      </Head>

      <a href="/index.html" className="logo">RR</a>
      <div className="nav-toggle-container">
        <div className="nav-toggle-menu">Menu</div>
        <button className="nav-toggle-bars">
          <div className="nav-bar-top"></div>
          <div className="nav-bar-middle"></div>
          <div className="nav-bar-bottom"></div>
        </button>
      </div>

      <section className="top">
        <div className="top-content">
          <h3>TOP POST</h3>
          <h1>This is the Top Post</h1>
        </div>
      </section>

      <section className="past">
        <div className="article">
          <h2>Previous Article 1</h2>
          <p>Lorum ipsum yadda, yadda, yadda...</p>
        </div>
        <div className="article">
          <h2>Previous Article 2</h2>
          <p>Lorum ipsum yadda, yadda, yadda...</p>
        </div>
      </section>

    </div>
  )
}

export default Index